version: 2

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - revive
    - errcheck
    - ineffassign
    - govet
    - staticcheck
    - misspell
    - unparam
    - prealloc
    - unconvert
    - gocritic
    - gocyclo
    - gocognit
    - asciicheck
    - bodyclose
    - nakedret
    - gosec
    - nilerr
    - exhaustive
    - gomodguard
    - whitespace
    - unparam
    - makezero