version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  disable:
    - errcheck

  enable:
    - ineffassign
    - govet
    - staticcheck
    - misspell
    - unparam
    - unconvert
    - gocritic
    - asciicheck
    - bodyclose
    - nakedret
    - gosec
    - nilerr
    - gomodguard
    - unparam
    - makezero