name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

env:
  HUGO_VERSION: '0.140.2'

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install dependencies
      run: |
        if [ -f "package.json" ]; then
          npm ci
        fi

    - name: Build documentation
      run: |
        hugo --minify
    - name: Upload artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: hugo-site
        path: ./public
        retention-days: 1

  deploy:
    name: Deploy to Cloudflare Pages
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: hugo-site
        path: ./public

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: lacquer-docs
        directory: ./public
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref || github.ref_name }}
        wranglerVersion: '3'